apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  labels:
    app: jaeger
    jaeger-infra: kibana-configmap
data:
  kibana.yml: |
    server:
      name: "tracing-kibana"
      port: 127.0.0.1:5601
    elasticsearch.url: "http://elasticsearch:9200"