apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: jaeger
    jaeger-infra: kibana-service
spec:
  type: LoadBalancer
  ports:
  - name: "ui"
    port: 5601
    targetPort: 5601
  selector:
    app: jaeger-kibana
    