apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: jaeger
    jaeger-infra: logstash-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jaeger-logstash
        jaeger-infra: logstash-replica
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:6.2.4
        ports:
        - containerPort: 5044
        env:
        - name: ES_VERSION
           valueFrom:
              configMapKeyRef:
                name: jaeger-configuration
                key: elasticsearch_version
        - name: LOGSTASH_PIPELINE_PORT
           valueFrom:
              configMapKeyRef:
                name: jaeger-configuration
                key: logstash_pipeline_port
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/logstash/config
          - name: logstash-pipeline-volume
            mountPath: /usr/share/logstash/pipeline
        #resources:
          #limits:
           # cpu:    1.0
           # memory: 500Mi
          #requests:
           # cpu:    0.5
            #memory: 300Mi
      volumes:
      - name: config-volume
        configMap:
          name: jaeger-configuration
          items:
            - key: logstash.yml
              path: logstash.yml
      - name: logstash-pipeline-volume
        configMap:
          name: jaeger-configuration
          items:
            - key: logstash.conf
              path: logstash.conf
  