apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash
  labels:
    app: jaeger
    jaeger-infra: logstash-configmap
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    config.reload.automatic: true
    ## Disable X-Pack
    ## see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
    xpack.monitoring.enabled: false
  logstash.conf: |
    input {
      tcp {
        port => 5044
      }
    }
    filter {
      json {
        source => "message"
      }
    }
    output {
      elasticsearch {
       hosts => ["elasticsearch:9200"]
       index => "mma-%{+YYYY-MM-dd}-logstash"
      }
    }


